apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharedfs
  namespace: default-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sharedfs
