apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/D1abloRUS/argocd.git
    targetRevision: HEAD
    path: cdi
  destination:
    server: https://kubernetes.default.svc
    namespace: cdi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
